sailsindocker:
      image: sailsindocker
      ports:
       - "1337:1337"
      environment:
        # ENV: TEST
        ENV: PROD
      # volumes:
      #  - .:/src
      links:
       - dnmonster
       - redis_server
dnmonster:
  image: amouat/dnmonster:latest
redis_server:
  image: redis

# 不建议用container做开发,所以comment off了volumes
# ENV:TEST 将执行 npm test,因为run完tests即退出，所以用 docker-compose up
# ENV:PROD 将执行 npm start,因为process不会结束,所以可以用 docker-compose up -d 在后台执行
